#!/usr/bin/bash

set +ex

./update.sh

echo "sending 30 second warning via server chat..."
# ./rcon sends the command to the server console via screen (local, no RCON).
./rcon "say 'server restarting for updates in 30 seconds'"
sleep 30

echo "30 seconds is up, restarting..."
systemctl restart minecraft_server

echo "done"
